# Generated by Django 4.1.7 on 2023-02-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=180)),
                ('name', models.CharField(max_length=180)),
            ],
        ),
    ]
